/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.helloworld

import kotlin.test.Test
import kotlin.test.assertEquals


class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = Library()
        assertEquals("Hello-world", classUnderTest.someLibraryMethod())
    }
}
